# Generated by Django 4.0.4 on 2022-05-07 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_pesme', models.CharField(max_length=100)),
                ('izvodjac', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('zanr', models.CharField(max_length=30)),
                ('tonalitet', models.CharField(max_length=3)),
                ('takt', models.CharField(max_length=10)),
                ('tempo', models.IntegerField()),
                ('ritam', models.CharField(max_length=30)),
                ('sekcije', models.CharField(max_length=50)),
                ('forspil', models.TextField()),
                ('strofa', models.TextField()),
                ('predrefren', models.TextField(blank=True)),
                ('refren', models.TextField()),
                ('drugo', models.TextField(blank=True)),
                ('aranzman', models.CharField(max_length=100)),
                ('za_pocetnike', models.BooleanField(default=False)),
                ('odobrio_admin', models.BooleanField(default=False)),
                ('datum_dodavanja', models.DateTimeField(default=django.utils.timezone.now)),
                ('dodao', models.CharField(max_length=50)),
            ],
        ),
    ]
