# Generated by Django 4.0.4 on 2022-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesma',
            name='drugo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesma',
            name='predrefren',
            field=models.TextField(blank=True, null=True),
        ),
    ]
