# Generated by Django 4.0.4 on 2022-06-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pesmarica', '0002_alter_pesma_drugo_alter_pesma_predrefren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesma',
            name='dodao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
