# Generated by Django 4.0.4 on 2022-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0003_alter_pesma_dodao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesma',
            name='za_pocetnike',
        ),
        migrations.AddField(
            model_name='pesma',
            name='tezina',
            field=models.CharField(choices=[('Za početnike', 'Za početnike'), ('Srednje', 'Srednje'), ('Teško', 'teško')], default='Za početnike', max_length=12),
        ),
    ]
