# Generated by Django 4.0.4 on 2022-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0005_remove_pesma_tezina_pesma_za_pocetnike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesma',
            name='za_pocetnike',
        ),
        migrations.AddField(
            model_name='pesma',
            name='tezina',
            field=models.CharField(default='Za početnike', max_length=12),
        ),
    ]
