# Generated by Django 4.0.4 on 2022-06-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0006_remove_pesma_za_pocetnike_pesma_tezina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesma',
            name='tezina',
            field=models.CharField(choices=[('Za početnike', 'Za početnike'), ('Srednje', 'Srednje'), ('Teško', 'Teško')], default='Za početnike', max_length=12),
        ),
    ]
