# Generated by Django 4.0.4 on 2022-06-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0007_alter_pesma_tezina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izvodjac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_albuma', models.CharField(max_length=250)),
                ('izvodjac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesmarica.izvodjac')),
            ],
        ),
        migrations.AlterField(
            model_name='pesma',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesmarica.album'),
        ),
        migrations.AlterField(
            model_name='pesma',
            name='izvodjac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesmarica.izvodjac'),
        ),
    ]
