# Generated by Django 4.0.4 on 2022-05-28 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesmarica', '0002_alter_pesma_drugo_alter_pesma_predrefren'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesma', models.ManyToManyField(to='pesmarica.pesma')),
            ],
        ),
        migrations.CreateModel(
            name='Repertoar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('javno', models.BooleanField(default=True)),
                ('datum_dodavanja', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pesma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repertoar.set')),
            ],
        ),
    ]
