# Generated by Django 4.0.4 on 2022-05-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0002_alter_pesma_drugo_alter_pesma_predrefren'),
        ('repertoar', '0003_alter_repertoar_set_delete_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesma', models.ManyToManyField(to='pesmarica.pesma')),
            ],
        ),
        migrations.AlterField(
            model_name='repertoar',
            name='set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repertoar.set'),
        ),
    ]
