# Generated by Django 4.0.4 on 2022-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesmarica', '0002_alter_pesma_drugo_alter_pesma_predrefren'),
        ('repertoar', '0004_set_alter_repertoar_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoar',
            name='set',
        ),
        migrations.AddField(
            model_name='repertoar',
            name='set',
            field=models.ManyToManyField(to='pesmarica.pesma'),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
