# Generated by Django 4.0.4 on 2022-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoar', '0005_remove_repertoar_set_repertoar_set_delete_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoar',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
