# Generated by Django 4.0.4 on 2022-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoar', '0006_alter_repertoar_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoar',
            name='opis',
            field=models.TextField(),
        ),
    ]
